# Generated by Django 5.2.6 on 2025-09-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='affiliation',
            old_name='sub_title',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='affiliation_org',
            old_name='sub_title',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='choosing',
            old_name='sub_title',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='flexibility',
            old_name='sub_title',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='mission',
            old_name='sub_title',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='mission_vision',
            old_name='sub_title',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='sub_title',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='reasons_for_choosing',
            old_name='sub_title',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='sub_title',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='sub_title',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='special',
            old_name='sub_title',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='sub_title',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='sub_title',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='value',
            old_name='sub_title',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='vision',
            old_name='sub_title',
            new_name='description',
        ),
        migrations.AddField(
            model_name='flexibility',
            name='title',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
