# Generated by Django 5.2.6 on 2025-09-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_affiliation_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choosing',
            name='image',
            field=models.ImageField(default=None, max_length=200, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='flexibility',
            name='image',
            field=models.ImageField(default=None, max_length=200, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(default=None, max_length=200, upload_to='images/'),
        ),
    ]
