# Generated by Django 5.2.6 on 2025-09-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_choosing_image_flexibility_image_story_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexibility',
            name='image',
            field=models.ImageField(blank=True, default=None, max_length=200, upload_to='images/'),
        ),
    ]
