# Generated by Django 5.2.6 on 2025-09-14 07:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_flexibility_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Success_story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(default=None, max_length=200, upload_to='images/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
