# Generated by Django 5.2.1 on 2025-09-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_value_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='icon_class',
            field=models.CharField(default='fa-star', max_length=50),
        ),
    ]
