# Generated by Django 5.2.1 on 2025-09-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_project_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexibility',
            name='icon_class',
            field=models.CharField(default='fa-star', max_length=50),
        ),
    ]
